### ISSUE TITLE
The method 'hashValues' isn't defined

### ISSUE THREAD

**Issue by fatihdurmaz** [albert-heijn-technology/apple_maps_flutter#67]
**Describe the bug**
Error: The method 'hashValues' isn't defined for the class 'InfoWindow'. after flutter upgrade to 3.27
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15 Pro]
 - Version [e.g. 18.2]

**flutter doctor**
Please add the `flutter doctor` output.

**Comment by praiaBarryTolnas** [comment]
[Here is the PR](https://github.com/flutter/flutter/pull/96109) where this migration was done for flutter/flutter packages.

**Comment by xonaman** [comment]
Please let us know when it’s live on pub.dev!

**Comment by Anjula** [comment]
I forked and replaced the hashValues. Try using this. 
[https://github.com/Anjula/apple_maps_flutter](https://github.com/Anjula/apple_maps_flutter)

 ```
 apple_maps_flutter:
    git:
      url: https://github.com/Anjula/apple_maps_flutter.git
      ref: cb853b3f3b86b3453559bf35f632696bb0357234
```

**Comment by ChrisMarxDev** [comment]
@xonaman 
I think you can add a dependency override for the `apple_maps_flutter ` dependency and it should work.
e.g.
```
dependency_overrides:
    apple_maps_flutter:
       git:
         url: https://github.com/Anjula/apple_maps_flutter.git
         ref: cb853b3f3b86b3453559bf35f632696bb0357234
```
